### ISSUE TITLE
Policies does not work, invalid input method

### ISSUE THREAD

**Issue by gfrid** [Scalr/sample-tf-opa-policies#36]
all policies work only after changing 

from this:
r := tfplan.resource_changes[_]
resource := tfplan.resource_changes[_]

to this:

r := input.resource_changes[_]
resoruce  := input.resource_changes[_]

examples: https://spacelift.io/blog/what-is-open-policy-agent-and-how-it-works

**Comment by rtfee** [comment]
@gfrid sorry for the late reponse. It depends on how you import the plan. That might work in their case, but in Scalr it is imported as tfplan and input.resource_changes[] doesn't actually exist. Here is an example of what a policy mock in Scalr looks like:

`  "tfplan": {
    "format_version": "1.1",
    "terraform_version": "1.3.3",
    "variables": {
      "instance_type": {
        "value": "t2.nano"
      }
    },
    "planned_values": {
      "outputs": {
        "instance_id": {
          "sensitive": false
        },
        "private_ip": {
          "sensitive": false
        },
        "public_ip": {
          "sensitive": false
        }
      },
      "root_module": {
        "resources": [
          {
            "address": "aws_instance.scalr",
            "mode": "managed",
            "type": "aws_instance",
            "name": "scalr",
            "provider_name": "registry.terraform.io/hashicorp/aws",
            "schema_version": 1,
            "values": {
              "ami": "ami-2757f631",
              "credit_specification": [],
              "get_password_data": false,
              "hibernation": null,
              "instance_type": "t2.nano",
              "key_name": "ryan",
              "launch_template": [],
              "source_dest_check": true,
              "subnet_id": "subnet-0ebb1058ad727cfdb",
              "tags": null,
              "timeouts": null,
              "user_data_replace_on_change": false,
              "volume_tags": null,
              "vpc_security_group_ids": [
                "sg-0880cfdc546b123ba"
              ]
            },
            "sensitive_values": {
              "capacity_reservation_specification": [],
              "credit_specification": [],
              "ebs_block_device": [],
              "enclave_options": [],
              "ephemeral_block_device": [],
              "ipv6_addresses": [],
              "launch_template": [],
              "maintenance_options": [],
              "metadata_options": [],
              "network_interface": [],
              "private_dns_name_options": [],
              "root_block_device": [],
              "secondary_private_ips": [],
              "security_groups": [],
              "tags_all": {},
              "vpc_security_group_ids": [
                false
              ]
            }
          }
        ]
      }
    },
    "resource_changes": [
      {`

See more here: https://www.scalr.com/blog/opa-series-part-1-open-policy-agent-and-terraform

**Comment by sachasmart** [comment]
As someone who though they were losing their mind, this comment helped immensely.
